### ISSUE TITLE
Is this project actively maintained? does it work with Angular 18?

### ISSUE THREAD

**Issue by FrancescoBorzi** [9von10/ngx-cytoscapejs#20] opened 2024-07-18 12:23 UTC
Greetings and first of all thanks for developing this application and making it open-source.

I'm considering using this library for a work project where we have Angular and already use cytoscape. My only concern is making sure this is regularly up to date.

We currently use Angular 17 and plan to move soon to Angular 18, I was wondering if you already support Angular 18 (I don't see it in the readme) and if you plan to actively update this library in the future to make sure it is compatible with the latest Angular version.

**Comment by 9von10** [comment] 2024-07-22 16:16
Hello Francesco,

thank you for your issue and your interest in ngx-cytoscapejs!

The library is currently working with Angular 18 but you must use the manual installation steps described in the README as the ng-add command throws a dependency error.
When using standalone components you have to import the module using the "importProvidersFrom" function from "@angular/core":

```ts
// app.config.ts
import { CytoscapejsModule } from 'ngx-cytoscapejs';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    importProvidersFrom(CytoscapejsModule),
  ],
};
```

Afterwards you can import the module in your standalone component and use the ngx-cytoscapejs component as intended:

```ts
// app.component.ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, CytoscapejsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
```

```html
<!-- app.component.html -->
<div class="full-height">
  <cytoscapejs
    [cytoscapeOptions]="cytoscapeOptions"
    [autoFit]="true"
    [applyCxBackgroundColor]="true"
  ></cytoscapejs>
</div>

<router-outlet />
```

As for regular updates: I'm planing to keep the library in sync with major Angular releases but will not add new features to it.
Because I'm working on this project in my free time it might take some time before an upgrade on my end will be released.
Currently I'm working on updating the library to Angular 18 and switching to standalone.

Best regards
Remo

**Comment by FrancescoBorzi** [comment] 2024-07-23 15:42
@9von10 thank you very much for your answer! I'm glad to hear you plan to maintain ngx-cytoscapejs, I will try using this library in my project.

**Comment by eboukamza** [comment] 2024-08-20 12:12
`CytoscapejsModule` has been removed from 1.8.0 

See [demo app](https://github.com/9von10/ngx-cytoscapejs/blob/main/projects/demo-app/src/app/app.component.ts#L15)

**Comment by 9von10** [comment] 2024-08-20 17:17
Hi @eboukamza ,

since version [1.8.0](https://github.com/9von10/ngx-cytoscapejs/blob/main/CHANGELOG.md#180-2024-08-02) the library is standalone and modules are therefore not needed anymore.

If you want to use the library with a module based Angular 18 app you can simply [import the component into your module](https://v17.angular.io/guide/standalone-components#using-standalone-components-in-ngmodule-based-applications).

**Closed as completed** 2024-08-25 10:31 UTC
Labels: enhancement, good first issue
